### ISSUE TITLE
Issue running the script. Session is set. 

### ISSUE THREAD

**Issue by Patrikkk** [cwyrwas/ChatGPT-Content-Generator#1]
PS H:\GitHub\ChatGPT-Content-Generator> python content_gen.py
Would you like to provide a topic for the video? (y/n) y
What topic would you like to write about? Motivation
Would you like to provide a tone for the video? (y/n) y
What tone would you like to write about? empowering, not giving up, pushing hard
Would you like to specify the length of the video? (y/n) y
How long should the video be? (in seconds) 15
Topic: Motivation
Tone: empowering, not giving up, pushing hard
Length: 15 seconds
Traceback (most recent call last):
  File "H:\GitHub\ChatGPT-Content-Generator\content_gen.py", line 41, in <module>
    video_script = get_video_script(session_token, video_topic, video_tone, video_length) # Get the video script from the AI.
  File "H:\GitHub\ChatGPT-Content-Generator\chat_gpt_interface.py", line 34, in get_video_script
    chatbot = Chatbot(config, conversation_id=None)
  File "C:\Users\patri\AppData\Local\Programs\Python\Python310\lib\site-packages\revChatGPT\revChatGPT.py", line 34, in __init__
    self.refresh_session()
  File "C:\Users\patri\AppData\Local\Programs\Python\Python310\lib\site-packages\revChatGPT\revChatGPT.py", line 214, in refresh_session
    raise Exception("Wrong response code")
Exception: Wrong response code

**Comment by cwyrwas** [comment]
I'm looking into this. Will get back to you shortly
