### ISSUE TITLE
Cookie error

### ISSUE THREAD

**Issue by Thrqureshi** [cwyrwas/ChatGPT-Content-Generator#2]
Hi 

I don't know whether it is a session 

Length: 81 seconds
Waiting for cookies...
Traceback (most recent call last):
  File "C:\Users\User\Desktop\Python\ChatGPT-Content-Generator\content_gen.py", line 41, in <module>
    video_script = get_video_script(session_token, video_topic, video_tone, video_length) # Get the video script from the AI.
  File "C:\Users\User\Desktop\Python\ChatGPT-Content-Generator\chat_gpt_interface.py", line 36, in get_video_script
    response = chatbot.get_chat_response(prompt, output="text")
  File "C:\Users\User\Desktop\Python\ChatGPT-Content-Generator\revChatGPT\revChatGPT.py", line 552, in get_chat_response
    return asyncio.run(coroutine_object)
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 646, in run_until_complete
    return future.result()
  File "C:\Users\User\Desktop\Python\ChatGPT-Content-Generator\revChatGPT\revChatGPT.py", line 258, in get_chat_response
    return await self.__get_chat_text(data)
  File "C:\Users\User\Desktop\Python\ChatGPT-Content-Generator\revChatGPT\revChatGPT.py", line 214, in __get_chat_text
    response = json.loads(response)
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

could you please let me know what is the issue here

**Comment by jgbrwn** [comment]
same issue.  This is after the chrome/selenium window pops up and the openai login screen shows and it appears to not be able to successfully login to openai perhaps (or we never see a success), then the window closes and we get the error.
